rules:
  # specifies the maximum cyclomatic complexity allowed in a program
  cyclomatic-complexity:
    severity: none
    options: 11

  # specifies curly brace conventions for all control statements
  curly:
    severity: error

  # requires default case in switch statements
  switch-default:
    severity: error


  # requires the use of === and !==
  triple-equals:
    severity: error

  # makes sure for-in loops have an if statement
  forin:
    severity: error

  # disallows the use of alert, confirm, and prompt
  ban:
    severity: warning
    options:
      - alert
      - confirm
      - prompt

  # disallows use of arguments.caller or arguments.callee
  no-arg:
    severity: error

  # disallows empty functions, except for standalone funcs/arrows
  no-empty:
    severity: error

  # disallows use of eval()
  no-eval:
    severity: error

  # disallows fallthrough of case statements
  no-switch-case-fall-through:
    severity: error

  # disallows this keywords outside of classes or class-like objects
  no-invalid-this:
    severity: none

  # disallows use of labels for anything other then loops and switches
  label-position:
    severity: error

  # disallows magic numbers
  no-magic-numbers:
    severity: none

  # disallows use of multiple spaces
  no-multi-spaces:
    severity: error
    options:
      exceptions:
        PropertyAssignment: false

  # disallows use of new operator when not part of the assignment or comparison
  # disallows usage of expressions in statement position
  no-unused-expression:
    severity: error
    options:
      - allow-fast-null-checks

  # disallows creating new instances of String, Number, and Boolean
  no-construct:
    severity: error

  # disallows usage of __proto__ property
  ter-no-proto:
    severity: error

  # disallows declaring the same variable more then once
  no-duplicate-variable:
    severity: error

  # disallows use of `javascript:` urls.
  ter-no-script-url:
    severity: error

  # disallows comparisons where both sides are exactly the same
  ter-no-self-compare:
    severity: error

  # restricts what can be thrown as an exception
  no-string-throw:
    severity: error

  # requires use of the second argument for parseInt()
  radix:
    severity: error
