rules:
  # disallows or enforce trailing commas (recommended)
  trailing-comma:
    severity: error
    options:
      multiline: never
      singleline: never

  # disallows assignment in conditional expressions
  no-conditional-assignment:
    severity: error

  # disallows use of console
  no-console:
    severity: warning

  # disallows use of constant expressions in conditions
  no-constant-condition:
    severity: warning

  # disallows control characters in regular expressions
  no-control-regex:
    severity: error

  # disallows use of debugger
  no-debugger:
    severity: error

  # disallows a duplicate case label.
  no-duplicate-case:
    severity: error

  # disallows empty statements
  no-empty:
    severity: error

  # disallows the use of empty character classes in regular expressions
  no-empty-character-class:
    severity: error

  # disallows assigning to the exception in a catch block
  no-ex-assign:
    severity: error

  # disallows double-negation boolean casts in a boolean context
  no-extra-boolean-cast:
    severity: error

  # disallows unnecessary semicolons
  no-extra-semi:
    severity: error

  # disallows function or variable declarations in nested blocks
  no-inner-declarations:
    severity: error

  # disallows invalid regular expression strings in the RegExp constructor
  no-invalid-regexp:
    severity: error

  # disallows irregular whitespace outside of strings and comments
  ter-no-irregular-whitespace:
    severity: error

  # disallows multiple spaces in a regular expression literal
  no-regex-spaces:
    severity: error

  # disallows sparse arrays
  ter-no-sparse-arrays:
    severity: error

  # avoid code that looks like two expressions but is actually one
  no-unexpected-multiline:
    severity: error

  # disallows return/throw/break/continue inside finally blocks
  no-unsafe-finally:
    severity: error

  # disallows comparisons with the value NaN
  use-isnan:
    severity: error

  # ensures JSDoc comments are valid
  valid-jsdoc:
    severity: none

  # ensures that the results of typeof are compared against a valid string
  valid-typeof:
    severity: error
