rules:
  # enforces no braces where they can be omitted
  ter-arrow-body-style:
    severity: error
    options:
      - as-needed
      - requireReturnForObjectLiteral: false

  # requires parens in arrow function arguments
  arrow-parens: false
  ter-arrow-parens:
    severity: error
    options:
      - as-needed
      - requireForBlockBody: true

  # requires space before/after arrow function's arrow
  ter-arrow-spacing:
    severity: error
    options:
      before: true
      after: true

  # requires let or const instead of var
  no-var-keyword:
    severity: error

  # requires method and property shorthand syntax for object literals
  object-literal-shorthand:
    severirty: error

  # suggests using arrow functions as callbacks
  ter-prefer-arrow-callback:
    severirty: error
    options:
      allowNamedFunctions: false
      allowUnboundThis: true

  # suggests using of const declaration for variables that are never modified after declared
  prefer-const:
    severirty: error
    options:
      destructuring: any
