rules:
  # enforce spacing inside array brackets
  array-bracket-spacing:
    severity: error
    options: never

  # enforce spacing inside single-line blocks
  block-spacing:
    severity: error
    options: always

  # enforce one true brace style
  brace-style:
    severity: error
    options:
      - 1tbs
      - { allowSingleLine: true }

  # require camel case names
  variable-name:
    severity: error
    options: check-format

  # disallow padding inside computed properties
  ter-computed-property-spacing:
    severity: error
    options: never

  # enforce newline at the end of file, with no multiple empty lines
  eofline:
    severity: error

  # enforce spacing between functions and their invocations
  ter-func-call-spacing:
    severity: error
    options: never

  # this option sets a specific tab width for your code
  indent: false
  ter-indent:
    severity: error
    options: 
      - 2
      -
        SwitchCase: 1
        VariableDeclarator: 1
        outerIIFEBody: 1
        # MemberExpression: null
        FunctionDeclaration:
          parameters: 1
          body: 1
        FunctionExpression:
          parameters: 1
          body: 1
        CallExpression:
          arguments: 1
        # ArrayExpression: 1
        # ObjectExpression: 1
        # ImportDeclaration: 1
        # flatTernaryExpressions: false

  # disallow mixed 'LF' and 'CRLF' as linebreaks
  linebreak-style:
    severity: error
    options: LF

  # specify the maximum length of a line in your program
  ter-max-len:
    severity: error
    options:
      - 120
      - 2
      -
        ignoreUrls: true
        ignoreComments: false
        ignoreRegExpLiterals: true
        ignoreStrings: true
        ignoreTemplateLiterals: true

  # specify the max number of lines in a file
  max-file-line-count:
    severity: warning
    options: 500

  # disallow the omission of parentheses when invoking a constructor with no arguments
  new-parens:
    severity: error

  # allow/disallow an empty newline after var statement
  ter-newline-after-var:
    severity: none

  # disallow use of bitwise operators
  no-bitwise:
    severity: error

  # disallow mixed spaces and tabs for indentation
  ter-no-mixed-spaces-and-tabs:
    severity: error

  # disallow multiple empty lines and only one newline at the end
  no-consecutive-blank-lines:
    severity: error
    options: 2

  # disallow trailing whitespace at the end of lines
  no-trailing-whitespace:
    severity: error

  # require padding inside curly braces
  object-curly-spacing:
    severity: error
    options: always

  # allow just one var statement per function
  one-variable-per-declaration:
    severity: error
    options: ignore-for-loop

  # disallow padding within blocks
  ter-padded-blocks:
    severity: error
    options: never

  # require quotes around object literal property names
  object-literal-key-quotes:
    severity: error
    options: as-needed

  # specify whether double or single quotes should be used
  quotemark:
    severity: error
    options:
      - single
      - avoidEscape
      - jsx-double

  # require or disallow use of semicolons instead of ASI
  semicolon:
    severity: error
    options: always

  sort-imports:
    severity: none

  # require or disallow spaces inside parentheses
  space-in-parens:
    severity: error
    options: never

  # require or disallow a space immediately following the # or /* in a comment
  comment-format:
    severity: error
    options:
      - check-space

  ter-no-tabs:
    severity: error