rules:

  # disallows declaration of variables already declared in the outer scope
  no-shadowed-variable:
    severity: error

  # disallows declaration of variables that are not used in the code
  # no-unused-variable:
  #   severity: error

  # disallows use of variables before they are defined
  no-use-before-declare:
    severity: error
