extends:
  - tslint-consistent-codestyle

rules:
  no-collapsible-if:
    severity: error

  early-exit:
    severity: error
    options:
      max-length: 5

  no-accessor-recursion:
    severity: error

  no-else-after-return:
    severity: error

  # Disabled as it does not work as expected at the moment
  # no-unnecessary-type-annotation:
  #   severity: error

  no-unused:
    severity: error

  no-var-before-return:
    severity: error
    options: allow-destructuring

  naming-convention:
    severity: error
    options:
      -
        type: default
        format: camelCase
        leadingUnderscore: forbid
        trailingUnderscore: forbid

      -
        type: parameter
        modifiers: unused
        leadingUnderscore: allow

      -
        type: variable
        modifiers: [global, const]
        format: [camelCase, UPPER_CASE]

      -
        type: interface
        prefix: I

      -
        type: type
        format: PascalCase

      -
        type: enumMember
        format: PascalCase